# /srv/mosdns/config.yaml
log:
  level: info

plugins:
  # 缓存
  - tag: tag_cache
    type: cache
    args:
      size: 10240
      lazy_cache_ttl: 259200
      dump_file: ./cache.dump
      dump_interval: 3600

  # 转发至本地服务器 DoH服务器
  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: dnspod_main
          addr: "https://1.12.12.12/dns-query"
        - tag: alidns_main
          addr: "https://223.5.5.5/dns-query"
        - tag: alidns_backup
          addr: "https://223.6.6.6/dns-query"
  # 转发至远程服务器 Clash
  - tag: forward_remote
    type: forward
    args:
      concurrent: 2
      upstreams:
        - tag: clash_udp
          addr: "127.0.0.1:5352"
        - tag: clash_tcp
          addr: "tcp://127.0.0.1:5352"
          enable_pipeline: true

  # fallback 用本地服务器 sequence
  # 返回不包含本地 ip 则 reject
  - tag: local_ip_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: resp_ip &./CN-ip-cidr.txt
        exec: accept
      - exec: drop_resp
  # fallback 用远程服务器 sequence
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote
      - exec: accept
  # fallback 用远程服务器 sequence
  - tag: tag_fallback
    type: fallback
    args:
      primary: local_ip_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - matches: qtype 12
        exec: reject 0
      - matches: qtype 65
        exec: reject 0
      - matches: qname &./reject-list.txt
        exec: reject 0
      - exec: prefer_ipv4
      - exec: $tag_cache
      - matches: has_resp
        exec: accept
      - matches: qname &./direct-list.txt
        exec: $forward_local
      - matches: has_resp
        exec: accept
      - exec: $tag_fallback

  # 启动 udp 服务器。
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :5351
