name: bin_update

on: 
#   release:
#       types: [published]
#   push:
#       tags:
#       - 'v*'
#   branches: 
#       - master
    schedule:
        - cron: 0 9 * * 6
#   watch:
#       types: [started]
    workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-18.04

    steps:
    
    - name: Checkout
      uses: actions/checkout@master
 
    - name: Apt Update
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip curl git tar
        
    - name: Update Dashboard
      run: |
        cd \bin
        echo 下载官方面板
        curl -kfSL -o dashboard.zip  https://github.com/Dreamacro/clash-dashboard/archive/gh-pages.zip
        echo 下载Meta面板
        curl -kfSL -o dashboard_meta.zip  https://github.com/MetaCubeX/Razord-meta/archive/gh-pages.zip
        echo 下载yacd面板
        curl -kfSL -o yacd.zip  https://github.com/haishanh/yacd/archive/gh-pages.zip 
        echo 下载meta魔改yacd面板
        curl -kfSL -o yacd_meta.zip  https://github.com/MetaCubeX/Yacd-meta/archive/gh-pages.zip
        echo 面板更新完成！
        
    - name: Update GeoIP
      run: |
        cd \bin
        source version
        curl -kfSL -O https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb
        curl -kfSL -o cn_mini.mmdb https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/Country.mmdb
        curl -kfSL -o china_ip_list.txt https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt
        curl -kfSL -O https://raw.githubusercontent.com/P3TERX/ca-certificates.crt/download/ca-certificates.crt
        curl -kfSL -O https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat
        curl -kfSL -O https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat
        curl -kfSL -O https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt
        curl -kfSL -O https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt
        curl -kfSL -O https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt
        sed -i '/GeoIP_v*/'d version
        echo GeoIP_v=`date '+%Y%m%d'` >> version
        echo IP数据库及根证书文件更新完成！
    - name: Commit and push
      run: |
        git config --global user.email "gdfsnhsw@gmail.com" && git config --global user.name "Bot"
        git add . && git commit -m "自动更新最新Dashboard、地址库、根证书" || exit 0
        git push
        
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
