name: Update Subconverter_Alpha Core
on:
  push:
    branches: 
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "40 0 */3 * *"
  workflow_dispatch:
env:
  download_version: ''
  download_url: https://github.com/MetaCubeX/subconverter/releases/download
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main
    - name: Download Core
      run: |
        download_version=Alpha
        echo "download_version=${download_version}" >> ${GITHUB_ENV}
        archs=(linux64 armv7 aarch64)
        new_name=(amd64 armv7 arm64)
        mkdir tmp
        for((i=0;i<3;i++));do
          wget -P ./tmp "${download_url}/${download_version}/subconverter_${archs[i]}.tar.gz"
          mv ./tmp/subconverter_${archs[i]}.tar.gz ./tmp/subconverter-linux-${new_name[i]}
        done
    - name: Update
      run: |
        rm -fr ./bin/subconverter_alpha/*
        cp ./tmp/* ./bin/subconverter_alpha/
        rm -fr ./tmp
    - name: Commit and push
      run: |
        git config --global user.email "gdfsnhsw@gmail.com" && git config --global user.name "Bot"
        git add . && git commit -m "更新Subconverter内核至${download_version}" || exit 0
        git push
